### ISSUE TITLE
certificate changes on the hosted version?

### ISSUE THREAD

**Issue by cfs77** [pvasek/TfsBot#3]
Hi,
we are using your hosted version. 
First of all thanks a lot for this service.

Since two days we expierencing some problems.

![image](https://user-images.githubusercontent.com/37112783/52267249-de89f000-2938-11e9-9634-643df9b8d030.png)

Did you do any changes with the certifcate?

**Comment by pvasek** [comment]
The ssl certificate expired. I updated it so hopefully should work now again. 

Please, let me know if it's working for you again.

**Comment by cfs77** [comment]
It works again.
Thank you for the quick fix of this issue.
